### ISSUE TITLE
Tech Stack of choice??

### ISSUE THREAD

**Issue by ShaunWMusic** [BoroDevMeetup/jobsite-api#1]
Please leave a comment below of the tech stack that you'd like to use for building out the api.

**Comment by ShaunWMusic** [comment]
I'm most fluent in Ruby on Rails and Node.js, but would be willing to build this in Go Lang

**Comment by daemyonc** [comment]
Whatever language we use I think we should design in Swagger(I think that's how it works). https://swagger.io/solutions/api-development/
My brother integrated it with C#/.NET API for the project I'm working on with him.

**Comment by ShaunWMusic** [comment]
nice! we use swagger docs in my current job as well.

**Comment by robhenley** [comment]
My vote would be Ruby / Python (in that order) but I'll work to contribute with whatever is chosen.
